# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4efa11a5e88218cc3f5641b46c57edbb3a4cd70af4e35707de408a5d1543cfd84202322138cd3d478d2eff49b2d8e98a91d8839ad71a25bd611ece7a1130bb76

test:
  secret_key_base: b9102e3bc285302084fc630e5c9be43cbcb11c181151e9df7b60fc1b39af2d91a4548174578d805ae1bd30040ac2fec832b24999bc1928b4eeefe1ba3a37ca8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
